---
# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build all using the local pdflatex
    cmds:
      - task: cv
      - task: resume
  clean:
    desc: Remove the out, log, aux, and pdf files
    cmds:
      - rm -f *.out
      - rm -f *.log
      - rm -f *.aux
      - rm -f *.pdf
  cv:
    desc: Build cv.pdf using the local latexmk
    cmds:
      - latexmk -pdf -interaction=nonstopmode -file-line-error cv.tex
  deps:
    desc: Install some dependencies
    cmds:
      - sudo apt install lacheck texlive-latex-extra
  docker:
    desc: Build resume.pdf and cv.pdf using the texlive Docker image
    cmds:
      - task: docker-cv
      - task: docker-resume
  docker-cv:
    desc: Build cv.pdf using the texlive Docker image
    cmds:
      - docker run --rm -v $(pwd):$(pwd) -w $(pwd) --user $(id -u):$(id -g) texlive/texlive latexmk -pdf -interaction=nonstopmode -file-line-error cv.tex
  docker-resume:
    desc: Build resume.pdf using the texlive Docker image
    cmds:
      - docker run --rm -v $(pwd):$(pwd) -w $(pwd) --user $(id -u):$(id -g) texlive/texlive latexmk -pdf -interaction=nonstopmode -file-line-error resume.tex
  lint:
    desc: Lint yaml, tex, and check spelling
    cmds:
      - docker run --rm -v $(pwd):$(pwd) -w $(pwd) --user $(id -u):$(id -g) texlive/texlive lacheck resume.tex
      - docker run --rm -v $(pwd):$(pwd) -w $(pwd) --user $(id -u):$(id -g) texlive/texlive lacheck cv.tex
      - yamllint-rs .
      - task: spellcheck
  sort:
    desc: Sort dictionary.txt
    cmds:
      - sort dictionary.txt -u -o dictionary.txt
  spellcheck:
    desc: Spellcheck files
    cmds:
      - python3 scripts/generate_typos_config.py
      - typos
  spellcheck-file:
    desc: Spellcheck a single file
    cmds:
      - python3 scripts/generate_typos_config.py
      - typos {{shellQuote .FILE}}
  resume:
    desc: Build resume.pdf using the local latexmk
    cmds:
      - latexmk -pdf -interaction=nonstopmode -file-line-error resume.tex
  default:
    cmds:
      - task -l
    silent: true
