---
name: ci
on:
  push:
    paths:
    - '**.tex'

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: texlive-action
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Check pdf files
        run: |
          file resume.pdf | grep -q ' PDF '
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'resume.pdf'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
