---
name: ci
'on':
  push:
    paths:
      - '**.tex'

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      -
        name: Set current date as env variable
        run: echo "now=$(date +'%Y-%m-%dT%H%M')" >> $GITHUB_ENV
      -
        name: texlive-action
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      -
        name: Check pdf files
        run: |
          file resume.pdf | grep -q ' PDF '
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.now }}
          release_name: ${{ env.now }}
          draft: false
          prerelease: false
      -
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'resume.pdf;cv.pdf'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.now }}
