---
name: ci
on:
  push:
    paths:
    - '**.tex'

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: texlive-action
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          asset_paths: '["./resume.pdf"]'
