---
name: ci
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
