---
name: lint
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.tex'
    branches:
      - main
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.tex'
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: ./.yamllint
      - name: 'lacheck'
        run: |
          apt install lacheck
          lacheck resume.tex
          lacheck cv.tex
