---
name: lint
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.tex'
    branches:
      - main
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.tex'
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Cache cargo'
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-yamllint-rs
      - name: 'yamllint-rs'
        run: |
          cargo install yamllint-rs
          yamllint-rs -c .yamllint .
      - name: 'lacheck'
        run: |
          sudo apt-get install -y lacheck
          lacheck resume.tex
          lacheck cv.tex
      - name: 'Generate typos config'
        run: python3 scripts/generate_typos_config.py
      - name: 'Spellcheck'
        uses: crate-ci/typos@v1.22.9
